### ISSUE TITLE
ConfigurationService - introduce TryGetConfigSection method

### ISSUE THREAD

**Issue by jazzman55** [CShark-Hub/Mako.IoT.Home#69]
Method should follow .NET's _TrySomething_ pattern:
bool TryGetConfigSection(string sectionName, Type objectType, out object section)
If section is found it should return _true_ and set _section_, otherwise it should return _false_.

**Comment by torbacz** [comment]
Done https://github.com/CShark-Hub/Mako-IoT.Device.Services.Configuration/pull/24
